### ISSUE TITLE
Cron not running

### ISSUE THREAD

**Issue by honzatmn** [zpanel/zpanelx#212] opened 2014-05-11 23:35 UTC
Hi, I added three crons for every minute and I can see them in my ZPanel > Advanced > Cron Manager, but they are not running.
If I run PHP script from browser, it works fine - there is no error in my script (paths for includes are absolute: /var/zpanel/hostdata/zadmin/public_html/domain_tld/script.php)

Thanks,
darkwindcz

OS: Ubuntu 12.04.4 LTS
ZPanel: 10.1.1
PHP: 5.3.10-1ubuntu3.11 with Suhosin-Patch

**Comment by jd1pinoy** [comment] 2014-05-12 00:09
This should be asked in zPanel Forum Official Support.

**Comment by honzatmn** [comment] 2014-05-12 00:14
Sorry, but I don't understand why - in zPanel Forum is many questions exactly like this - so it is not only my problem - and there is no solution to this issue. I installed zPanel to the clean Ubuntu server, I don't modified anything.

**Comment by jd1pinoy** [comment] 2014-05-12 00:19
You need to create your own thread and support staff or helpful community members will answer and help you solve your issue.

zPanelX Git is for collaboration of codes and scripts, not the place to ask support, I hope you understand.

Here's the link and create your thread issue:
http://forums.zpanelcp.com/Forum-General-Support-Questions

Thanks

**Comment by honzatmn** [comment] 2014-05-12 00:32
Ok, sorry about that. I wrote to similar topic in the forum nad I hope that there will be someone who can help us... Thanks!

**Comment by ghost** [comment] 2014-05-12 07:16
Closing. USE THE FORUMS FOR SUPPORT.

This is not a bug not an issue and the support team will be happy to reply @:

http://forums.zpanelcp.com/

THANKS

**Closed as completed by ghost** 2014-05-12 07:16 UTC

**Comment by honzatmn** [comment] 2014-05-12 08:38
We discussed it in the forum, and jd1pinoy said that is a bug ... (http://forums.zpanelcp.com/Thread-Problem-with-cron?page=3)

**Comment by ghost** [comment] 2014-05-12 08:52
We will log it later still checking this issue...
Better you report bugs via forum then we compile the issues for developers and look for solutions SIR.

M B
