### ISSUE TITLE
Ubuntu 12.04 POP3 Fail

### ISSUE THREAD

**Issue by QQingsandQQueens** [zpanel/zpanelx#173] opened 2014-03-31 09:52 UTC
Clean install on ubuntu 12.04 server via curl. POP3 fails

**Comment by trojanspike** [comment] 2014-03-31 09:57
Make sure the ports are let through your firewall.
110
143

**Comment by ghost** [comment] 2014-05-12 07:19
Closing. USE THE FORUMS FOR SUPPORT.

This is not a bug not an issue and the support team will be happy to reply @:

http://forums.zpanelcp.com/

THANKS

**Closed as completed by ghost** 2014-05-12 07:19 UTC
