### ISSUE TITLE
Updates lol ? :

### ISSUE THREAD

**Issue by IPFaN** [zpanel/zpanelx#249] opened 2014-09-06 11:22 UTC
You appear to be running a BETA release, unless you are testing or developing we recommend you download and use the latest stable release (10.0.0).

**Comment by IPFaN** [comment] 2014-09-06 11:22
i run 10.1.1 ???

**Comment by jacobgelling** [comment] 2014-09-08 16:22
Duplicate of #246

**Closed as completed** 2014-09-09 20:05 UTC
Labels: duplicate
