### ISSUE TITLE
2-part Proftpd Core Module

### ISSUE THREAD

**Issue by zHostingSolutions** [zpanel/zpanelx#167] opened 2014-03-26 21:57 UTC
Proftpd Login:
- This will enable the ability to log into Proftpd and configure the ftp server by launching it from the control panel and entering the given login info after installing zPanel on Linux.

Override password:
- This module will allow the ability to change the password just in case the password doesn't work after the installation of zpanel, or if server admin just wants to change the password to something that he/she can remember.

**Comment by ghost** [comment] 2014-03-27 08:11
IS this a feature request? Please explain better IF there is a module you want to push of improvement over current.

Notice for features request it would be better if you discuss them on forum first as this is ISSUES tracker and we focus on BUGS first. Unless you want to fork the project and build the feature you want.

Me.B

**Comment by jacobgelling** [comment] 2014-03-30 09:22
@zHostingSolutions People have posted multiple times to stop posting feature requests here - **use the forum!**

**Comment by 5050** [comment] 2014-03-30 13:22
As it was already asked MANY times to use the forum for every thing that is not a bug, i'll close this report too.

**Closed as completed by 5050** 2014-03-30 13:22 UTC

**Comment by zHostingSolutions** [comment] 2014-04-01 03:43
@Me-Bl yes, it's a feature request.
