### ISSUE TITLE
New domains not working

### ISSUE THREAD

**Issue by honzatmn** [zpanel/zpanelx#211] opened 2014-05-11 23:29 UTC
Hi, 
I have added new domain, after few minutes it goes to status "live" (with 5 minute daemon), but after reaching that domain in the browser it shows login form for zpanel.

DNS was ok, there isn't error. After manual restart of my server it works ok.

Thanks,
darkwindcz

OS: Ubuntu 12.04.4 LTS
ZPanel: 10.1.1
PHP: 5.3.10-1ubuntu3.11 with Suhosin-Patch

**Comment by jd1pinoy** [comment] 2014-05-12 00:10
This should be asked in zPanel Forum Official Support.

**Comment by honzatmn** [comment] 2014-05-12 00:16
... it looks like a problem for many users, not only for me. I found the same issues in the forum, so it definitely looks like a bug.
I added my OS configuration for better analyzation of this issue...

**Comment by ghost** [comment] 2014-05-12 07:16
Closing. USE THE FORUMS FOR SUPPORT.

This is not a bug not an issue and the support team will be happy to reply @:

http://forums.zpanelcp.com/

THANKS

**Closed as completed by ghost** 2014-05-12 07:16 UTC
